# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    
    http_client:
        default_options:
            max_redirects: 7

        scoped_clients:
            seller_api:
                base_uri: 'https://seller.com/'
            
            buyer_api:
                base_uri: 'https://buyer.com/'
                # HTTP Basic authentication
                auth_basic: 'the-username:the-password'
                # HTTP Bearer authentication (also called token authentication)
                auth_bearer: the-bearer-token    
 
            
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
