twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        tracking: '1233454'
    form_themes: ['bootstrap_5_layout.html.twig']    
        
when@test:
    twig:
        strict_variables: true

    