controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\UserController::number

app_string:
    path: /string
    controller: App\Controller\UserController::string

api_user_show:
    path:       /api/user/{id}
    controller: App\Controller\UserController::getUserDetails
    methods:    GET|HEAD    

user_search:
  path:        /user/{_locale}/search.{_format}
  controller:  App\Controller\UserController::search
  locale:      en
  format:      html
  requirements:
      _locale: en|fr
      _format: html|xml  

user_extra_params:
    path:       /user_params/{page}
    controller: App\Controller\UserController::extraParams
    defaults:
        page: 1
        title: "Hello world!"

user:
    path:
        en: /about-us
        nl: /over-ons
    controller: App\Controller\UserController::about   


url_generatingUrl:
    path: /generatingUrl
    controller: App\Controller\UserController::generatingUrl            