# config/validator/validation.yaml
App\Entity\User:
    properties:
         name:
            - NotBlank: ~
            

App\Entity\Contact:
    properties:
        firstname:
            - NotBlank: ~
            - Length:
                min: 2
                max: 5
            
        lastname:
            - NotBlank: ~
            - Length:
                min: 2
                max: 5

App\Entity\UsersWork:
    properties:
        startdate:
            - Date: ~         